flags: {}
extra-package-dbs: []
resolver: lts-14.15
packages:
- 'lib'
- 'pcf'
- 'scheme'
# - 'while'
# - 'stratego'
# - 'jimple'
# - 'tutorial'
extra-deps:
  - dump-core-0.1.3.2
  - monadLib-3.10
  - git: https://github.com/farrellm/husk-scheme/
    commit: 5aaf41968dafa66301c847d1b5f63f8e8073275d
  - knob-0.1.1
