name:                sturdy-lambdajs
version:             0.1.0.0
license:             BSD3
maintainer:          Sven Keidel <svenkeidel@gmail.com>
category:            Language

dependencies:
  - base
  - hashable
  - mtl
  - profunctors
  - sturdy-lib
  - random
  - text
  - transformers
  - unordered-containers
  - containers
  - LambdaJS

library:
  source-dirs:
    - src

  ghc-options: -Wall


tests:
  spec:
    main: Spec.hs

    source-dirs:
      - test

    ghc-options: -Wall

    dependencies:
      - hspec
      - sturdy-while
